defaults:
  - z_L_prior: null

_target_: model.decoder.LadderDecoder
num_blocks_per_scale: 1  # number of resnet blocks after each latent variable
num_postprocess_blocks: 1  # number of resnet blocks after the 'last' (z_1) latent variables
num_ch: ${model.num_ch}
scale_ch_mult: ${model.scale_ch_mult}
block_ch_mult: ${model.block_ch_mult}
data_ch: ${dataset.image_size[0]}
data_dim: ${dataset.image_size[1]}
latent_scales: ${model.latent_scales}
latent_width: ${model.latent_width}
weight_norm: ${model.weight_norm}
batch_norm: ${model.batch_norm}
padding_mode: ${model.padding_mode}
likelihood: ${model.likelihood}
num_mix: ${model.num_mix}
activation: ${model.activation}
start_scale_at_x: ${model.start_scale_at_x}
min_logvar: -8
decoder_res_mode: 2x3