---
defaults:
  - optimizer: adamax
  - scheduler: cosine

seed: 123
start_epoch: 0
image_size: ${dataset.image_size}
resume_id: null
pretrain_id: null
ema_rate: 0.999
acc_grad: 1
grad_clip: 5.0
grad_skip_thr: 0
max_epochs: 300
early_stopping_epochs: 150
device: 'cuda:0' 
eval_freq: 2
ddp: false
use_amp: false
compute_fid: False
fid_on_train: False
lr_warup_epochs: 2
only_test: False # only run a test loop
max_iter_per_epoch: null
optimizer:
  lr: 0.01
  weight_decay: 1e-6
scheduler:
  T_max: 300
  eta_min: 1e-5
